### ISSUE TITLE
Default to iGEM distribution

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#89] opened 2016-10-25 17:33 UTC
The default "local" repository should be some sort of commonly useful collection, like one of the iGEM plate distributions (e.g., http://parts.igem.org/assembly/libraries.cgi?id=66)

**Comment by cjmyers** [comment] 2016-11-25 16:54
Let's select an interesting iGEM collection of parts to make the built-in parts.

**Comment by cjmyers** [comment] 2016-11-28 14:59
One option would be to use a built-in library of commonly re-used parts.  The question would be where to draw the cutoff:
>50 reuses : 86 parts
>40 reuses : 120 parts
>30 reuses : 148 parts
>20 reuses : 237 parts
>10 reuses : 500 parts
>5 reuses : 1174 parts
>0 reuses : 6288 parts

**Comment by jakebeal** [comment] 2016-11-28 15:13
Rather than making a guess based on use frequency, I would recommend using one of the library distributions suggested by iGEM, found on the following page http://parts.igem.org/assembly/libraries.cgi

For the most high-quality and up-to-date library, I would suggest the most recent distribution: http://parts.igem.org/assembly/libraries.cgi?id=66

Yes, there's a lot in there, but it's been specifically curated to be a useful variety of parts.

**Comment by cjmyers** [comment] 2016-11-28 15:52
The tricky thing about that is that unless the parts have been noted as being part of a distribution in the SQL database, then actually building this file would be a very tedious manual process of grabbing the parts one by one OR writing some sort of script to scrap this data off the website you listed below.  It might be in the SQL dump, but we are finding that not everything on the website and the SQL dump match perfectly.

The built-in library is not meant to be anything near complete, but rather just something small that can be distributed with the software for simple practice with the tool.  Users should use the SBOL version of the iGEM registry for the whole dataset.  

BTW: the SBOL iGEM registry is nearing a stable release point.  We are still tweaking the script to ensure that all information is captured well within SBOL.  Indeed, if you are interested, we would be happy to have another set of eyes to look at what we are doing in the translation.

**Comment by jakebeal** [comment] 2016-11-28 15:57
I suspect iGEM may be willing to help: ask Traci tomorrow?

**Comment by michael13162** [comment] 2016-11-30 23:08
Is there any news on this?

**Comment by cjmyers** [comment] 2016-11-30 23:40
I was thinking to write a simple program to pull down the most frequently used parts to build this file.  However, Jake wanted this to be a distribution of parts.  I just checked, and there is no indication of a part being in a distribution in Randy’s SQL data.  Therefore, there is no way to generate this file except by manually fetching each individual part on the plates listed on the website from the stack, one-by-one.  This is likely not feasible.  

The dataset does though have a Status and Results fields.  There are 2014 parts that are marked as Available and Works, respectively.  This could be a good set perhaps.

Jake: what do you think?  

BTW: you can see our SBOL encoding of iGEM now directly from the iGEM registry website.  If you pick a part, select part tools -> SBOL Format, it will give you back what we currently are storing in the SynBioHub SBOL Stack.  Comments are very welcome.

**Comment by michael13162** [comment] 2017-05-29 23:53
I have updated the BuiltInParts with what Chris sent me.

**Comment by cjmyers** [comment] 2017-06-03 22:57
I've uploaded the 2017 iGEM distribution to dropbox here:

https://www.dropbox.com/s/g3pwttphv19pvkw/iGEM_2017.xml?dl=0

I believe this is the file that Jake intended for built-in parts when he first logged this issue.  These are the actual parts that iGEM students receive from iGEM.

**Comment by cjmyers** [comment] 2017-06-08 23:45
I've updated the built-in parts file.  However, the registry dialog does not seem to filter correctly.  Namely, I don't think I'm getting the right parts for the role selected.  Also, there are no Collections showing up.  Would hope behavior is same as if you want to see these parts in SynBioHub.

**Comment by michael13162** [comment] 2017-06-11 06:25
Chris has confirmed that everything is fixed.

**Closed** 2017-06-11 06:44 UTC
Labels: bug, priority
