### ISSUE TITLE
Remember last selected collection

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#163] opened 2017-06-08 05:10 UTC
In addition to remembering the last selecting registry, also remember the last selected collection.

**Comment by michael13162** [comment] 2017-06-11 07:42
Punting to 2.3 due to time constraints.

**Comment by michael13162** [comment] 2017-09-04 19:33
This is a duplicate of https://github.com/SynBioDex/SBOLDesigner/issues/154.

**Closed by michael13162** 2017-09-04 19:33 UTC
Labels: change
