### ISSUE TITLE
Missing displayIds causing problems

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#143] opened 2017-02-02 22:50 UTC
When opening a file that is missing displayId, you start to get errors about missing displayIds when you bring the design into your namespace.  This is likely due to createCopy requiring displayIds.  Hmm, not sure if there is any easy workaround...

**Comment by michael13162** [comment] 2017-02-02 22:55
If the problem is indeed an issue with the namespace requirements, then a "hacky" workaround is to set your personal namespace to match that of the part in the document.  This way, you should be able to add displayIds and avoid the wrong namespace errors.

**Comment by cjmyers** [comment] 2017-02-02 23:00
It is actually a “bug” in libSBOLj.  You are getting this error in createCopy.  When displayIds are missing, it attempts to extract one from the identity, but it only does this for top-level objects.  It should also try to do this for child objects.  Assuming something could be extracted, then this would solve the problem.

**Comment by michael13162** [comment] 2017-02-02 23:06
Oh, I see.  This "bug" is quite a good find then.  I've sent @mgaldzic a link to this issue.  We can continue the conversation here.

**Comment by cjmyers** [comment] 2017-02-02 23:30
libSBOLj now extracts displayIds during copy for child objects, if necessary.  This eliminates the exception for missing displayIds, and the URIs appear to be created correctly.  However, the sequences have disappeared after bringing into my namespace.  Suspect this is a larger bug when bringing into local namespace.

**Comment by cjmyers** [comment] 2017-02-26 19:29
A file outside your namespace with no displayId, then you need to try to edit it.  Bring into your namespace, and then the sequence disappeared.

**Comment by michael13162** [comment] 2017-04-05 21:10
This was a bug in libSBOLj right?

**Comment by cjmyers** [comment] 2017-04-05 22:32
At least partially, but I was losing sequences after the libSBOLj changes, I believe.  I have not seen this recently though, but I think it occurred when we tried to open files without displayIds that we got from Michal Galdzicki.

**Comment by michael13162** [comment] 2017-04-17 03:41
I just tested this with an SBOLDocument where I removed a displayId, and I was able to give it a displayId and have the Sequence persist, so the libSBOLj fix might have fixed it here too.  I am closing the issue for now.

**Closed by michael13162** 2017-04-17 03:41 UTC
Labels: bug
