### ISSUE TITLE
Create Collection filter

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#98] opened 2016-11-25 16:26 UTC
Start with All Root Collections
Text box should only include root collections
Collection in text box when selected, should filter by that collection, then update combo box to put that collections displayId on top of the list in the combo box.
Select a Collection in the combo box, re-fliter by that collection

**Comment by michael13162** [comment] 2016-11-29 06:50
This is implemented but needs further testing.  I'm getting a bug where stack collection querying freezes 1/10 attempts.  I think this might be a stack bug, but unsure.  Chris, can you reproduce by clicking around?

**Comment by cjmyers** [comment] 2016-11-29 20:26
We checked the log and the problem is you are trying to call fetchComponent using the URI for a collection. The stack ends up trying to fetch the Collection and all its members and build you that SBOL file which is huge, so it times-out.  Granted the fetchComponent method should fail once it determines the URI does not point to a ComponentDefinition, but since it does not this approach does not work right now.  The code in question is here:


RegistryInputDialog.java
	protected void handleTableSelection() {
		// handle collection selected
		if (isMetadata()) {
			int row = table.convertRowIndexToModel(table.getSelectedRow());
			IdentifiedMetadata meta = ((IdentifiedMetadataTableModel) table.getModel()).getElement(row);
			try {
				stack.fetchComponent(URI.create(meta.uri));
			} catch (StackException e1) {
				updateCollectionSelection(false, meta);
				updateTable();
				return;
			}
		}
		canceled = false;
		setVisible(false);
	}

I think the best solution might be to add another column in the table on the far left called Type.  For now, it could say either Collection OR Part.  If we want to get clever, we could change these to icons, but for now the word will do.  This will make it also easier for the user to know which are Collections and which are Parts.  You can then use this field to know whether to fetch the component or the collection metadata.

Chris

**Comment by michael13162** [comment] 2016-11-29 23:02
Ah, I see.  My code here was intentional.  I hoped that trying to fetch a component using a collection URI would cause an exception, which would then be caught and call the updateCollectionSelection() method with the collection to insert.  This was a "dirty" way to tell if an identified metadata was a collection or not.  

Another option I saw was filling in the description of collections with a "collection" keyword, and then the user could filter by description, which I've added.  Assuming the stack had a method like "isCollection" or "tryFetchComponent", then this would fix the problem without needing to complicate the IdentifiedMetadataTableModel/Table with fields that don't inherently belong in IdentifiedMetadata.

However, either way works.  How do you and James feel about this?  It could be useful to have those methods, or even make it so "fetchComponent" doesn't try to build a giant SBOLDocument when a collection URI is passed in.  It could just fail, which makes sense as well.

**Comment by cjmyers** [comment] 2016-11-29 23:07
I agree that it would be useful to fix the Java API.  

However, I think it is still useful for the user to be able to see which are Collections and which are Parts.  This is similar to having a different icon for Folders and Files in a file browser.  Therefore, my preference would be to widen the part search window a small amount to add this “Type” field as a new leftmost column.  This would enable one to also sort the Collections to the top if they like.  We could also use that column for other type information in the future, such as perhaps CD type.

**Comment by michael13162** [comment] 2016-11-29 23:11
Yes, displaying icons and potentially having part icons have text like "CD" in them would be very useful.

I'll create a wrapper for IdentifiedMetadata that will store this additional information and display either "Collection" or "Part" for now.

**Comment by michael13162** [comment] 2016-11-30 17:01
I've updated the table with a column that has either collection or part now.  I will now work on getting the collections combo box to have the correct collections listed.

**Comment by cjmyers** [comment] 2016-11-30 20:50
I checked in fix that has it removing the collections below the selected one.  Please check.

**Comment by michael13162** [comment] 2016-11-30 22:01
Looks good!  I also replaced combo box displaying collection name to collection displayId.

I'm closing the issue since I think all features are met.

**Closed by michael13162** 2016-11-30 22:01 UTC
Labels: enhancement, priority
