### ISSUE TITLE
Read/Write SBOL 1.1, GenBank, FASTA

### ISSUE THREAD

**Issue by michael13162** [SynBioDex/SBOLDesigner#11] opened 2016-05-13 16:49 UTC
Give the user an option to write in multiple formats as well as SBOL 2.0.

**Comment by michael13162** [comment] 2016-05-23 20:36
Added inital implementation, but SBOLWriter has issues.

-writing GenBank fails if there are any SAs with GenericLocation instead of Range/Cut, even though the design does also have SAs with Range/Cut.
-writing FASTA output a .rdf file.  Isn't it supposed to be .fas?

**Comment by cjmyers** [comment] 2016-05-23 20:51
> On May 23, 2016, at 2:36 PM, Michael Zhang <notifications@github.com> wrote:
> 
> Added inital implementation, but SBOLWriter has issues.
> 
> -writing GenBank fails if there are any SAs with GenericLocation instead of Range/Cut, even though the design does also have SAs with Range/Cut.
> 
I think this is correct behavior.  If you have any components with GenericLocation, they cannot currently be encoded within GenBank.  GenBank only works when all sequences are defined.  You should catch this exception, check the message, and report to the user that all parts must have a sequence to be serialized.

One option for something with partial sequences, might be to use a cut.  For example, let’s say you have three components, one with sequence of length 10 from 1 to 10, next with no sequence, so a Cut at 10, and third with a sequence of length 10 from 11 to 20.  I think this is closer to the intended behavior of the layout.  It shows where the Component will be inserted when defined.
> -writing FASTA output a .rdf file. Isn't it supposed to be .fas?
> 
> 
I cannot find anywhere in my code where I add a “.rdf”.  The fileName string is whatever you give it, I believe.  You could add the “.fas” to the file name when you call write for FASTA.

Chris

**Comment by michael13162** [comment] 2016-05-23 22:25
The components have an SA with GenericLocation as well as an SA with a Range, so there should be enough information to encode in GenBank.  However, because there is an additional SA with GenericLocation, SBOLWriter stops and reports it's unable to continue.  I'm not sure how this is implemented, but one way would be to look at all the SAs that refer to this component, and only report failure if none of them have a Range/Cut.

**Comment by cjmyers** [comment] 2016-05-23 22:43
Ah, I think you may have found a different bug.  You should not be able to have two SAs for the same Component.  I wonder how you managed this one.  The “setComponent” method does check for this.  I’m not sure how you could get around this.

**Comment by michael13162** [comment] 2016-05-23 22:51
Sorry, I actually do only have one SA.  However, that SA has multiple locations.  When an SA is first created, a GenericLocation is automatically added to its set of Locations.  Therefore, when I add Ranges later on, there are multiple Location objects attached to the SA.

**Comment by cjmyers** [comment] 2016-05-23 22:56
Ah, now that makes sense.  Yes, it should not throw an exception in that case.  You can log that one as a libSBOLj bug.

**Comment by michael13162** [comment] 2016-05-23 23:02
Done, thanks!

**Closed** 2016-05-25 17:03 UTC
