### ISSUE TITLE
Submit to an existing Collection

### ISSUE THREAD

**Issue by cjmyers** [SynBioDex/SBOLDesigner#170] opened 2017-08-30 23:29 UTC
It should be possible to submit to an existing collection.  In that case, you do not need to provide id/name/description.  See how this is done on SynBioHub.

**Comment by michael13162** [comment] 2017-09-19 04:08
Closing because duplicate of https://github.com/SynBioDex/SBOLDesigner/issues/175

**Closed by michael13162** 2017-09-19 04:08 UTC
Labels: enhancement, priority
