### ISSUE TITLE
registry import window appears only after click

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#214] opened 2018-01-16 11:50 UTC
Running SBOLDesigner-2.2 on my Mac, when I edit a part and request "import registry part", nothing happens.  Only after I click does the import window actually appear.

**Comment by michael13162** [comment] 2018-01-18 06:19
I've made some changes that might have fixed this issue.  It'd be nice if either @cjmyers or @jakebeal could test since this was only reproducible on macs.

Thanks!

**Comment by cjmyers** [comment] 2018-01-19 01:01
Seems to work for me.

**Comment by michael13162** [comment] 2018-01-19 04:02
If you're confident, feel free to close the issue. Thanks!

**Comment by cjmyers** [comment] 2018-01-20 05:46
Would be good to get confirmation from another mac user that experienced this.  @tramyn can you try this out?

**Comment by jakebeal** [comment] 2018-01-26 11:37
This is still happening to me with 3.0-prerelease.

**Comment by cjmyers** [comment] 2018-01-26 14:15
Strange.  I cannot reproduce this one anymore.  It was happening for me earlier.

Is the sequence Edit Part followed by Import Registry Part?

**Comment by jakebeal** [comment] 2018-01-27 03:42
I don't attempt to edit the sequence: I just create a component, double click, and then hit import registry.

**Comment by jakebeal** [comment] 2018-01-27 12:52
Also, why is this assigned to me to fix?

**Comment by cjmyers** [comment] 2018-01-27 16:22
In our workflow, when something needs testing, we assign it to the person who we think should test it.  In this case, that was you since we think it is fixed.  However, since you report it is not fixed for you, I've reassigned it back to Michael.  

This one is really strange.  @tramyn and myself saw this behavior also.  We were both using Mac, like you I presume.  We indeed found an issue which explained the problem, and I can no longer see this behavior from the current version.

Ok, I just tried the release, and I am indeed seeing this behavior @michael13162, are you sure the jar you posted is the latest and greatest?

**Comment by cjmyers** [comment] 2018-01-27 16:25
I just tried in the last Jar that I built, and it is also not showing up there.

@michael13162 my guess is you posted an older jar.

**Comment by cjmyers** [comment] 2018-01-29 17:01
Should be fixed now in latest JAR.  Please confirm @jakebeal

**Comment by jakebeal** [comment] 2018-01-29 17:31
Still broken for me, as of this morning's test.

**Comment by michael13162** [comment] 2018-01-29 17:51
This is very strange indeed.  @tramyn could you try it too?

**Comment by cjmyers** [comment] 2018-01-29 17:52
Drat. Must be difference between running in eclipse and jar

Chris

**Comment by cjmyers** [comment] 2018-01-29 18:22
Ok, I just tried running the standalone jar, java -jar SBOLDesigner-3.0.jar, and this does not happen.

However, if I click on the Jar and run it, I do see this behavior.  Not sure what is different between those ways of starting up.

@michael13162 have you ever tested this by click on the Jar to execute it rather than running in eclipse or doing java -jar?  Curious if this occurs on Windows too.

**Comment by michael13162** [comment] 2018-01-30 02:42
I just tried this and still can't reproduce it.  If the registry is set to Built-In parts, it takes about 2 seconds for the dialog to pop up (because it has to read in all the files).  If you click on open registry and just wait, are you sure it's not popping up after a bit?

With SynBioHub, it's instantaneous.

**Comment by cjmyers** [comment] 2018-01-30 03:14
Did you run by clicking on the jar?

Chris

**Comment by michael13162** [comment] 2018-01-30 03:17
Yes.  I tried it both ways actually.  No difference, unfortunately.

**Comment by cjmyers** [comment] 2018-01-30 03:27
I thought it was the delay too until I ran by double-click on jar, then it appeared.   So strange.

**Comment by cjmyers** [comment] 2018-01-30 04:00
Looks as if this is a JDK bug:

https://bugs.openjdk.java.net/browse/JDK-8179335 <https://bugs.openjdk.java.net/browse/JDK-8179335>

**Comment by michael13162** [comment] 2018-01-30 04:01
From that post:

This is limitation for Mac OS X 
Natively, there are 3 window levels. 0,1,2 
As far as it looks, with these limitations case 2 is an acceptable working mode as the focus is still on the active modal window. 
As window levels are not dynamic as in Windows, looks like there is no clean fix for this issue. 
Also, tapping on any window will bring the correct dialog to foreground.

**Comment by cjmyers** [comment] 2018-01-30 04:08
This post is linked to this issue which seems to indicate a fix was applied in October 2017

https://bugs.openjdk.java.net/browse/JDK-8182638

**Comment by cjmyers** [comment] 2018-01-30 04:10
This appears to be the fix:

http://hg.openjdk.java.net/jdk10/master/rev/19b912843392 <http://hg.openjdk.java.net/jdk10/master/rev/19b912843392>

Guess we can assume this problem will resolve when people update their JDK.  Maybe though there is a workaround if we can find a way to order the window to the front.

Chris

**Comment by cjmyers** [comment] 2018-01-30 04:23
I found this solution:

https://alvinalexander.com/blog/post/jfc-swing/input-focus-dialog-jdialog-java-swing-problem-solution <https://alvinalexander.com/blog/post/jfc-swing/input-focus-dialog-jdialog-java-swing-problem-solution>

Basically, I added this code to your InputDialog constructor:

		// this solves the problem where the dialog was not getting
		// focus the second time it was displayed
		SwingUtilities.invokeLater(new Runnable() 
		{  
			public void run() {  
				loginButton.requestFocusInWindow();
			}
		});

I think it has done the trick.

**Comment by cjmyers** [comment] 2018-01-30 04:24
I've updated the pre-release again.

**Comment by cjmyers** [comment] 2018-01-30 04:29
Ok, this is a bigger problem than I realized.  When I run the JAR directly, many windows are appearing behind other windows.  We would need to replicate my solution every time there are three windows open simultaneously.

**Comment by michael13162** [comment] 2018-02-02 00:29
I have been getting null pointer exceptions when opening certain dialogs because they don't have a loginButton.  (The fix above assumes there is always a login button)

**Comment by cjmyers** [comment] 2018-02-02 04:36
I see. Maybe always have a cancel button?

Chris

**Comment by michael13162** [comment] 2018-02-02 04:41
Done.  

I just took a look at the type hierarchy, and (funny enough) it turns out everything deriving from InputDialog retains the cancel button.

**Comment by cjmyers** [comment] 2018-02-02 16:00
Excellent.  These seems a good workaround.

**Comment by jakebeal** [comment] 2018-02-16 12:40
There is now no longer a delay, but instead an error box immediately appears saying it can't find the working document and I have to try again (error message can't be copy & pasted).  This happens twice, and then it gives up and lets me have the import box.

**Comment by cjmyers** [comment] 2018-02-16 18:09
Yes, I think I've seen that before.  The issue is that it remembers what your last registry choice was, and if it was Working Document and their is no Working Document, such as when you first startup you get this message.  This is a bug, but I think once you select a SynBioHub registry for example, you should not see these on subsequent imports.  @michael13162 can you see about addressing this messaging problem.  Maybe it should revert to built-in parts if the Working Document does not exist.   Or maybe there should always be a working document even when you first start.

**Comment by michael13162** [comment] 2018-02-23 01:17
I had a hard time reproducing exactly what you're describing, but I think I've fixed it so the import parts selection gets automatically chosen when there is no working document.  Also, when there is no working document yet, it will report an empty list of importable parts (which makes more sense than always telling the user I think).

**Comment by cjmyers** [comment] 2018-02-23 09:27
Ok, seems to be working.

**Closed by cjmyers** 2018-02-23 09:27 UTC
Labels: bug, needs testing
