### ISSUE TITLE
"Getting this selection failed:" blank

### ISSUE THREAD

**Issue by jakebeal** [SynBioDex/SBOLDesigner#235] opened 2018-01-26 11:41 UTC
In testing to see if #221 was resolved in 3.0-prerelease on my Mac, I attempted to import E0040 from the local registry. This pops up the following blank error:

![image](https://user-images.githubusercontent.com/10675899/35438254-67e7a122-025b-11e8-8541-a3f08820ba09.png)

**Comment by cjmyers** [comment] 2018-01-26 14:13
Yes, I can reproduce this too.

Michael: the problem is with built-in parts.  It seems this is no longer functional.  The same is true for working document.  I think with recent changes, the getting parts from files has broken.

**Comment by michael13162** [comment] 2018-01-26 21:56
Yup, there was a serious flaw in getSelection() in RegistryInputDialog that got introduced recently.  It should be fixed now.  I also fixed a bug in saving new versions regarding dangling component references.

**Comment by cjmyers** [comment] 2018-01-29 14:47
This appears to be working for me now.

**Comment by jakebeal** [comment] 2018-01-29 15:39
Binary to test?

**Comment by cjmyers** [comment] 2018-01-29 15:44
I’ve updated the Jar found here:

https://github.com/SynBioDex/SBOLDesigner/releases/tag/v3.0-beta <https://github.com/SynBioDex/SBOLDesigner/releases/tag/v3.0-beta>

**Comment by jakebeal** [comment] 2018-01-29 16:24
Works for me now.

**Closed** 2018-01-29 17:00 UTC
Labels: bug, needs testing
