### ISSUE TITLE
Problem while importing parts from private collection

### ISSUE THREAD

**Issue by Fontanapink** [SynBioDex/SBOLDesigner#304] opened 2018-09-05 20:55 UTC
I created a simple Transcriptional Unit in SBOLdesigner, and tried to import part from my private collection at https://synbiohub.utah.edu/.

I logged in succesfully, could find my private collection but couldn't find any parts in it (meaning it appeared empty for all parts). 
If I download the SBOLdocument from my private collection in https://synbiohub.utah.edu/, and then try to find the parts from the SBOLdocument instead, I can find the parts.

**Comment by michael13162** [comment] 2018-09-05 21:08
I've confirmed with Pedro that this isn't because of SBOLExplorer (the same issue occurs when I turn SBOLExplorer off).

**Comment by cjmyers** [comment] 2018-09-05 21:52
I think i know the issue.  If these parts are ones that were downloaded from synbiohub.org <http://synbiohub.org/> (or some other SBH), then re-uploaded then they don’t currently show up, since the query only returns parts that reside in the SBH that is being queried.  For now, you should be able to fetch them from the original source SBH location.

**Comment by Fontanapink** [comment] 2018-09-06 18:46
OK new developments in this issue. So, I encounter the same problem when trying to build my dCas9/CRISPR yeast gates, and I can't see ANY parts in my collection EXCEPT for the operator sites

**Comment by cjmyers** [comment] 2018-09-21 18:16
This is be addressed in issue #4 for SBOLExplorer, #701 for SynBioHub, and #312 for SBOLDesigner

**Closed by cjmyers** 2018-09-21 18:16 UTC
